# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class OcrTranslationPage(UniversalBaseModel):
    page_num: int = pydantic.Field()
    """
    1-indexed page number.
    """

    source_hash: str = pydantic.Field()
    """
    SHA-256 hash of the OCR content used for this translation.
    """

    source_language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detected source language for this page.
    """

    target_language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target language for this page.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Translated OCR HTML for the page.
    """

    status: str = pydantic.Field()
    """
    Page translation status.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Page-level translation error, if any.
    """

    is_stale: bool = pydantic.Field()
    """
    True when the current OCR content no longer matches the translated source hash.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
