# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class OcrJobResponse(UniversalBaseModel):
    job_id: uuid.UUID = pydantic.Field()
    """
    OCR job id.
    """

    file_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original file name.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
