# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .batch_audio_source import BatchAudioSource
import pydantic
from .transcription_request_info import TranscriptionRequestInfo
import uuid
from .processing_mode import ProcessingMode


class BatchTranscriptionRequest(UniversalBaseModel):
    audio_sources: typing.List[BatchAudioSource] = pydantic.Field()
    """
    List of audio sources to transcribe with the same settings.
    """

    info: TranscriptionRequestInfo = pydantic.Field()
    """
    Shared transcription parameters for all audio files in the batch
    """

    batch_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional title for the batch. The system will first check for a title in the Audio Source itself. If no title is provided there, it defaults to batch title providded here with "- Batch Item N" appended.
    """

    batch_id: typing.Optional[uuid.UUID] = pydantic.Field(default=None)
    """
    Optional ID for the batch. If not provided, a UUID will be generated.
    """

    processing_mode: typing.Optional[ProcessingMode] = pydantic.Field(default=None)
    """
    Processing speed and cost tier.
    - standard: (Default) Processed within 24 hours. Lower cost. 
    - express: Processed immediately. Higher cost. Limited to 10 files per batch.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
