# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import uuid
import pydantic
import datetime as dt
from .batch_file_status import BatchFileStatus
import typing


class BatchFileSummary(UniversalBaseModel):
    id: uuid.UUID = pydantic.Field()
    """
    ID of the batch file.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the manifest was uploaded.
    """

    item_count: int = pydantic.Field()
    """
    Number of items detected in the manifest.
    """

    size_bytes: int = pydantic.Field()
    """
    Size of the uploaded manifest in bytes.
    """

    status: BatchFileStatus = pydantic.Field()
    """
    Current validation status of the manifest.
    """

    checksum: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional checksum of the manifest payload.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional title from metadata.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
