# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ...core.pydantic_utilities import UniversalBaseModel
from .batch_file_metadata import BatchFileMetadata


class BatchFileCreateFromRssRequest(UniversalBaseModel):
    """
    Create a batch manifest by importing audio enclosures from a podcast RSS feed.
    """

    rss_url: str = pydantic.Field()
    """
    Public RSS feed URL to fetch and parse for podcast episode audio enclosures.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Optional maximum number of episodes to import. Defaults to the standard batch manifest limit.
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of podcast episode audio enclosures to skip before importing. Use `next_offset` from the previous response to fetch the next page.
    """

    metadata: typing.Optional[BatchFileMetadata] = pydantic.Field(default=None)
    """
    Optional title and description for this manifest. If omitted, the podcast title from the feed is used when available.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
