# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .batch_status import BatchStatus


class BatchSummary(UniversalBaseModel):
    """
    Current progress of a batch created from a manifest, without individual transcription payloads.
    """

    batch_id: uuid.UUID
    created_at: dt.datetime
    title: typing.Optional[str] = None
    status: BatchStatus
    total_count: int = pydantic.Field()
    """
    Total transcriptions expected in this batch, including items still being initialized.
    """

    completed_count: int = pydantic.Field()
    """
    Successfully completed transcriptions.
    """

    failed_count: int = pydantic.Field()
    """
    Failed or cancelled transcriptions, including insufficient-funds failures.
    """

    pending_count: int = pydantic.Field()
    """
    Transcriptions still queued, processing, or being initialized.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
