# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .language import Language
from .letters_language import LettersLanguage


class BatchTranscriptionRequestInfo(UniversalBaseModel):
    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model to be used for the transcription. Default is "v1".
    - v1: Our latest and most accurate model, especially for audio with longer stretches of Hebrew.
    Priced at 1.50 USD per hour of audio transcribed.
    - v0: Not generally recommended. Cheaper, but less accurate.
    Priced at 1.00 USD per hour.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title for the transcription, Default is "Untitled"
    """

    folder_id: typing.Optional[uuid.UUID] = pydantic.Field(default=None)
    """
    Optional owned document folder applied to every transcript created by this batch.
    """

    primary_language: typing.Optional[Language] = pydantic.Field(default=None)
    """
    Specifies the primary language spoken in the audio content. Default is English.
    - en: English
    - he: Hebrew
    - yi: Yiddish
    - fr: French
    """

    hebrew_word_format: typing.Optional[typing.List[LettersLanguage]] = pydantic.Field(default=None)
    """
    Relevant only when `primary_language` is `en`. This setting controls how Hebrew,
    Yiddish, and Aramaic speech is rendered across the batch.
    - Omit it or specify `["hybrid"]` (the default) to transliterate phrases of three
      words or fewer in italicized English letters and write longer phrases in Hebrew letters.
    - Specify `["he"]` to write all such speech in Hebrew letters.
    - Specify `["en"]` to transliterate all such speech into italicized English letters.
    - Specify `["en", "he"]` to provide every Hebrew word in both formats, with the
      transliteration in `<i>` tags.
    - When the primary language is not English, omit this field or specify `["he"]`;
      `["he"]` is the only supported format.
    """

    num_speakers: typing.Optional[int] = pydantic.Field(default=None)
    """
    Expected number of speakers in the audio. Default is 1. This field is mutually exclusive with `auto_detect_speakers`. If a number more than 1 is passed, it will be used for speaker labeling and adds **$0.30/hour**.
    """

    auto_detect_speakers: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Automatically detect the number of speakers in the audio. This field is mutually exclusive with `num_speakers`. If both are provided, the API returns a 400 error. Auto-detection adds **$0.30/hour**.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
