# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class BatchFileMetadata(UniversalBaseModel):
    """
    Optional metadata for organizing batch files.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name for this batch manifest
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Notes or description
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
