# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .batch_file_summary import BatchFileSummary


class ListBatchFilesResponse(UniversalBaseModel):
    files: typing.List[BatchFileSummary] = pydantic.Field()
    """
    Your uploaded batch manifests
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pagination cursor (if more results exist)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
