# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .language import Language
from .letters_language import LettersLanguage
from .status import Status
from .transcription_id import TranscriptionId


class TranscriptionInfo(UniversalBaseModel):
    id: TranscriptionId = pydantic.Field()
    """
    ID of the transcription
    """

    client_item_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller-defined per-item identifier for batch items. This is `null` for single transcriptions and for batch items submitted without a `client_item_id`.
    """

    title: str = pydantic.Field()
    """
    Title of the transcription
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the transcription was created
    """

    primary_language: Language = pydantic.Field()
    """
    The primary language of the audio content, which can be English (en), Hebrew (he), Yiddish (yi), or French (fr).
    """

    hebrew_word_format: typing.List[LettersLanguage] = pydantic.Field()
    """
    Indicates how Hebrew words are transcribed in the response when the primary language is English.
    - Hebrew words are in Hebrew letters if "he" is specified.
    - Hebrew words are transliterated into English letters if "en" is specified.
    - If both "he" and "en" are specified, both versions are provided back-to-back for each Hebrew word.
    Transliterated Hebrew words are surrounded by <i> tags in the response text.
    """

    num_speakers: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of speakers in the audio. This can be `null` while auto-detection is pending or if no count was determined.
    """

    status: Status = pydantic.Field()
    """
    Current status of the transcription
    """

    duration: typing.Optional[float] = pydantic.Field(default=None)
    """
    Duration of the audio in seconds. If None, it means the duration was not calculated yet.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model used for the transcription. V1 is the latest and most accurate model, especially for audio with longer stretches of Hebrew. V0 is suitable for audio with fewer Hebrew words.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
