# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ...core.pydantic_utilities import UniversalBaseModel


class TranscriptionTranslationRequest(UniversalBaseModel):
    target_mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    Translation target. Use auto to translate Hebrew/Yiddish/Aramaic-heavy segments to English and English-heavy segments to Hebrew.
    """

    translation_style: typing.Optional[str] = pydantic.Field(default=None)
    """
    Translation style id. Built-ins include learning_english and sefer_hebrew; saved user guides use custom:<style_id>.
    """

    force: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Regenerate the translation even if cached segments already exist.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
