# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class KnowledgeBaseSearchChunk(UniversalBaseModel):
    text: str = pydantic.Field()
    """
    Retrieved passage, including passages without reliable audio timing.
    """

    transcript_id: str = pydantic.Field()
    """
    ID of the authorized source document (including non-audio documents).
    """

    start_time: typing.Optional[float] = pydantic.Field(default=None)
    """
    Start in seconds, or null when audio alignment is unavailable or ambiguous.
    """

    end_time: typing.Optional[float] = pydantic.Field(default=None)
    """
    End in seconds, or null when audio alignment is unavailable or ambiguous.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
