# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from ...document_types.types.document_id import DocumentId
from .document_translation_segment import DocumentTranslationSegment
from .document_translation_target_language import DocumentTranslationTargetLanguage


class DocumentTranslationStatus(UniversalBaseModel):
    document_id: DocumentId = pydantic.Field()
    """
    Stable source document ID.
    """

    target_language: DocumentTranslationTargetLanguage = pydantic.Field()
    """
    Requested translation language. With `auto`, each segment reports its concrete language in its own `target_language` field.
    """

    translation_style: str = pydantic.Field()
    """
    Translation style ID used for this independently stored target-language translation.
    """

    status: str = pydantic.Field()
    """
    Overall translation status.
    """

    total_segments: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total paragraphs or pages in the translation job.
    """

    completed_segments: int = pydantic.Field()
    """
    Number of successfully translated paragraphs or pages.
    """

    failed_segments: int = pydantic.Field()
    """
    Number of failed paragraphs or pages.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the translation job was created.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the translation job was last updated.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Overall job error, if any.
    """

    source_word_count: int = pydantic.Field()
    """
    Total visible words across the document's current paragraphs or pages, including content that already has a current translation.
    """

    billable_word_count: int = pydantic.Field()
    """
    Words in missing, failed, forced, or stale segments that still need translation. Cached current segments are excluded, so this can be zero even when `source_word_count` is not.
    """

    estimated_api_cost_cents: float = pydantic.Field()
    """
    Estimated API balance reservation for the current `billable_word_count`, in cents, at USD 0.25 per 1,000 words. For example, `25` means USD 0.25 and `250` means USD 2.50. This is an estimate of remaining work, not a historical invoice, and normally becomes zero after all current segments are translated.
    """

    segments: typing.List[DocumentTranslationSegment] = pydantic.Field()
    """
    Paragraph- or page-level results for this target language and translation style.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
