# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .document_translation_target_language import DocumentTranslationTargetLanguage


class DocumentTranslationRequest(UniversalBaseModel):
    target_language: typing.Optional[DocumentTranslationTargetLanguage] = pydantic.Field(default=None)
    """
    Translation target language. Use `en` or `he`; omit it to use automatic
    English/Hebrew direction selection. Custom styles and language-specific
    built-ins require their explicit compatible target language.
    """

    translation_style: typing.Optional[str] = pydantic.Field(default=None)
    """
    Translation style ID. Built-ins are `default` for a clear natural translation,
    `learning_english` for polished Torah-learning English, and `sefer_hebrew` for
    traditional sefer-style Hebrew. Custom style IDs come from `/v1/translation-styles`.
    Omit this to use `default`. `learning_english` requires target language `en`,
    `sefer_hebrew` requires `he`, and each custom style declares its compatible language.
    """

    force: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Regenerate the translation even if cached content already exists.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
