# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from ...document_types.types.document_id import DocumentId


class Document(UniversalBaseModel):
    id: DocumentId = pydantic.Field()
    """
    Stable document ID.
    """

    type: str = pydantic.Field()
    """
    Document source type.
    """

    title: str = pydantic.Field()
    """
    Display title.
    """

    folder_id: typing.Optional[uuid.UUID] = pydantic.Field(default=None)
    """
    Containing folder, or null for root.
    """

    status: str = pydantic.Field()
    """
    Current document or processing status.
    """

    archived: bool = pydantic.Field()
    """
    Whether the document is archived.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Creation time.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Last update time, when available.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Visible plain text for completed text and transcript documents when available.
    """

    html: typing.Optional[str] = pydantic.Field(default=None)
    """
    Editor-compatible HTML for completed documents when available.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
