# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class StartingPhraseTopic(UniversalBaseModel):
    title: str = pydantic.Field()
    """
    Descriptive title of the topic
    """

    starting_phrase: str = pydantic.Field()
    """
    The phrase expected to occur near the start of this topic
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
