# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Document,
        DocumentCreateRequest,
        DocumentFilterType,
        DocumentFormat,
        DocumentListResponse,
        DocumentTranslationRequest,
        DocumentTranslationSegment,
        DocumentTranslationStatus,
        DocumentTranslationTargetLanguage,
        DocumentUpdateRequest,
    )
    from .errors import DocumentNotFound, DocumentTooLarge, FolderNotFound, InvalidCursor, InvalidDocument
_dynamic_imports: typing.Dict[str, str] = {
    "Document": ".types",
    "DocumentCreateRequest": ".types",
    "DocumentFilterType": ".types",
    "DocumentFormat": ".types",
    "DocumentListResponse": ".types",
    "DocumentNotFound": ".errors",
    "DocumentTooLarge": ".errors",
    "DocumentTranslationRequest": ".types",
    "DocumentTranslationSegment": ".types",
    "DocumentTranslationStatus": ".types",
    "DocumentTranslationTargetLanguage": ".types",
    "DocumentUpdateRequest": ".types",
    "FolderNotFound": ".errors",
    "InvalidCursor": ".errors",
    "InvalidDocument": ".errors",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Document",
    "DocumentCreateRequest",
    "DocumentFilterType",
    "DocumentFormat",
    "DocumentListResponse",
    "DocumentNotFound",
    "DocumentTooLarge",
    "DocumentTranslationRequest",
    "DocumentTranslationSegment",
    "DocumentTranslationStatus",
    "DocumentTranslationTargetLanguage",
    "DocumentUpdateRequest",
    "FolderNotFound",
    "InvalidCursor",
    "InvalidDocument",
]
