# This file was auto-generated by Fern from our API Definition.

import typing
import uuid
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..document_types.types.document_id import DocumentId
from ..transcribe.errors.authentication_error import AuthenticationError
from ..transcribe.errors.insufficient_api_balance import InsufficientApiBalance
from ..transcribe.errors.rate_limit_error import RateLimitError
from .errors.document_not_found import DocumentNotFound
from .errors.document_too_large import DocumentTooLarge
from .errors.folder_not_found import FolderNotFound
from .errors.invalid_cursor import InvalidCursor
from .errors.invalid_document import InvalidDocument
from .types.document import Document
from .types.document_filter_type import DocumentFilterType
from .types.document_format import DocumentFormat
from .types.document_list_response import DocumentListResponse
from .types.document_translation_status import DocumentTranslationStatus
from .types.document_translation_target_language import DocumentTranslationTargetLanguage

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawDocumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_document(
        self,
        *,
        title: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[uuid.UUID] = OMIT,
        format: typing.Optional[DocumentFormat] = OMIT,
        content: typing.Optional[str] = OMIT,
        file: typing.Optional[str] = OMIT,
        file_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Document]:
        """
        Create a durable document from plain text, Markdown, or a Word `.docx` file.

        Provide exactly one of `content` or `file`. Files must be base64 encoded. Text,
        Markdown, and Word ingestion completes synchronously. The returned `id` is the
        document ID used by every document, translation, and folder endpoint.

        Parameters
        ----------
        title : typing.Optional[str]
            Display title. Defaults to the file name without its extension or Untitled Document.

        folder_id : typing.Optional[uuid.UUID]
            Optional owned folder. Null or omitted creates the document at root.

        format : typing.Optional[DocumentFormat]
            Source format. Defaults to text for content and is inferred from file_name for files.

        content : typing.Optional[str]
            UTF-8 plain-text or Markdown content. Provide this or file, but not both.

        file : typing.Optional[str]
            Base64-encoded `.txt`, `.md`, or `.docx` file. Provide this or content, but not both.

        file_name : typing.Optional[str]
            Original file name. Used to infer format and title when those values are omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Document]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/documents/",
            method="POST",
            json={
                "title": title,
                "folder_id": folder_id,
                "format": format,
                "content": content,
                "file": file,
                "file_name": file_name,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 413:
                raise DocumentTooLarge(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise FolderNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_documents(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        folder_id: typing.Optional[uuid.UUID] = None,
        archived: typing.Optional[bool] = None,
        type: typing.Optional[DocumentFilterType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DocumentListResponse]:
        """
        List the authenticated API user's documents using cursor pagination.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        limit : typing.Optional[int]
            Number of documents to return. Defaults to 50 and cannot exceed 100.

        folder_id : typing.Optional[uuid.UUID]
            Return only documents in this folder. Omit to list documents across all folders.

        archived : typing.Optional[bool]
            Return archived or active documents. Defaults to false.

        type : typing.Optional[DocumentFilterType]
            Optionally filter by transcript or text document type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DocumentListResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/documents/",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "folder_id": folder_id,
                "archived": archived,
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentListResponse,
                    parse_obj_as(
                        type_=DocumentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise FolderNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidCursor(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_document(
        self, document_id: DocumentId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Document]:
        """
        Retrieve an owned document. A transcription ID returned by an existing
        transcription endpoint is already a document ID; no conversion is required.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Document]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_document(
        self,
        document_id: DocumentId,
        *,
        title: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[uuid.UUID] = OMIT,
        archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Document]:
        """
        Update document metadata. Omitted fields are unchanged. An explicitly null
        `folder_id` moves the document to root; a UUID moves it into that owned folder.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        title : typing.Optional[str]
            New display title. Omit to leave unchanged.

        folder_id : typing.Optional[uuid.UUID]
            Omit to leave unchanged, send null to move to root, or send an owned folder UUID.

        archived : typing.Optional[bool]
            Archive or restore the document. Archived documents are moved to root.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Document]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}",
            method="PATCH",
            json={
                "title": title,
                "folder_id": folder_id,
                "archived": archived,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_document_translation(
        self,
        document_id: DocumentId,
        *,
        target_language: typing.Optional[DocumentTranslationTargetLanguage] = OMIT,
        translation_style: typing.Optional[str] = OMIT,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DocumentTranslationStatus]:
        """
        Start a document translation. Text and transcript documents use paragraph-level
        translation.

        **API price:** USD 0.25 per 1,000 billable words, deducted from your API balance.
        Pricing is prorated to the word: 1,000 billable words costs USD 0.25 and 10,000
        billable words costs USD 2.50. Cached current paragraphs are free; stale, missing,
        failed, forced, or newly added paragraphs are billable.

        Repeated requests for the same document and translation configuration reuse
        cached work and the same billing identity, preventing duplicate charges.

        A document can have multiple translations. Each combination of target language and
        translation style is stored separately, so the same document can be translated
        into both English and Hebrew without duplicating the source document.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        target_language : typing.Optional[DocumentTranslationTargetLanguage]
            Translation target language. Use `en` or `he`; omit it to use automatic
            English/Hebrew direction selection. Custom styles and language-specific
            built-ins require their explicit compatible target language.

        translation_style : typing.Optional[str]
            Translation style ID. Built-ins are `default` for a clear natural translation,
            `learning_english` for polished Torah-learning English, and `sefer_hebrew` for
            traditional sefer-style Hebrew. Custom style IDs come from `/v1/translation-styles`.
            Omit this to use `default`. `learning_english` requires target language `en`,
            `sefer_hebrew` requires `he`, and each custom style declares its compatible language.

        force : typing.Optional[bool]
            Regenerate the translation even if cached content already exists.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DocumentTranslationStatus]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}/translations",
            method="POST",
            json={
                "target_language": target_language,
                "translation_style": translation_style,
                "force": force,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentTranslationStatus,
                    parse_obj_as(
                        type_=DocumentTranslationStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 402:
                raise InsufficientApiBalance(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_document_translation(
        self,
        document_id: DocumentId,
        target_language: DocumentTranslationTargetLanguage,
        *,
        translation_style: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DocumentTranslationStatus]:
        """
        Get the translation for a target language and style, including current status,
        remaining billable words, estimated API cost, and translated content.

        The service rebuilds the document's current paragraphs or pages and compares
        their hashes with the hashes stored during translation. Changed source content
        is returned as stale and becomes billable again when translation is requested.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        target_language : DocumentTranslationTargetLanguage
            Target language used when the translation was created, or `auto` for automatic direction selection.

        translation_style : typing.Optional[str]
            Translation style ID. Built-ins are `default`, `learning_english` for an
            English target, and `sefer_hebrew` for a Hebrew target. Omit this to use
            `default`. Custom style IDs come from `/v1/translation-styles`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DocumentTranslationStatus]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}/translations/{jsonable_encoder(target_language)}",
            method="GET",
            params={
                "translation_style": translation_style,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentTranslationStatus,
                    parse_obj_as(
                        type_=DocumentTranslationStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDocumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_document(
        self,
        *,
        title: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[uuid.UUID] = OMIT,
        format: typing.Optional[DocumentFormat] = OMIT,
        content: typing.Optional[str] = OMIT,
        file: typing.Optional[str] = OMIT,
        file_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Document]:
        """
        Create a durable document from plain text, Markdown, or a Word `.docx` file.

        Provide exactly one of `content` or `file`. Files must be base64 encoded. Text,
        Markdown, and Word ingestion completes synchronously. The returned `id` is the
        document ID used by every document, translation, and folder endpoint.

        Parameters
        ----------
        title : typing.Optional[str]
            Display title. Defaults to the file name without its extension or Untitled Document.

        folder_id : typing.Optional[uuid.UUID]
            Optional owned folder. Null or omitted creates the document at root.

        format : typing.Optional[DocumentFormat]
            Source format. Defaults to text for content and is inferred from file_name for files.

        content : typing.Optional[str]
            UTF-8 plain-text or Markdown content. Provide this or file, but not both.

        file : typing.Optional[str]
            Base64-encoded `.txt`, `.md`, or `.docx` file. Provide this or content, but not both.

        file_name : typing.Optional[str]
            Original file name. Used to infer format and title when those values are omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Document]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/documents/",
            method="POST",
            json={
                "title": title,
                "folder_id": folder_id,
                "format": format,
                "content": content,
                "file": file,
                "file_name": file_name,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 413:
                raise DocumentTooLarge(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise FolderNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_documents(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        folder_id: typing.Optional[uuid.UUID] = None,
        archived: typing.Optional[bool] = None,
        type: typing.Optional[DocumentFilterType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DocumentListResponse]:
        """
        List the authenticated API user's documents using cursor pagination.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque cursor returned by the previous page.

        limit : typing.Optional[int]
            Number of documents to return. Defaults to 50 and cannot exceed 100.

        folder_id : typing.Optional[uuid.UUID]
            Return only documents in this folder. Omit to list documents across all folders.

        archived : typing.Optional[bool]
            Return archived or active documents. Defaults to false.

        type : typing.Optional[DocumentFilterType]
            Optionally filter by transcript or text document type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DocumentListResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/documents/",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
                "folder_id": folder_id,
                "archived": archived,
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentListResponse,
                    parse_obj_as(
                        type_=DocumentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise FolderNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidCursor(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_document(
        self, document_id: DocumentId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Document]:
        """
        Retrieve an owned document. A transcription ID returned by an existing
        transcription endpoint is already a document ID; no conversion is required.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Document]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_document(
        self,
        document_id: DocumentId,
        *,
        title: typing.Optional[str] = OMIT,
        folder_id: typing.Optional[uuid.UUID] = OMIT,
        archived: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Document]:
        """
        Update document metadata. Omitted fields are unchanged. An explicitly null
        `folder_id` moves the document to root; a UUID moves it into that owned folder.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        title : typing.Optional[str]
            New display title. Omit to leave unchanged.

        folder_id : typing.Optional[uuid.UUID]
            Omit to leave unchanged, send null to move to root, or send an owned folder UUID.

        archived : typing.Optional[bool]
            Archive or restore the document. Archived documents are moved to root.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Document]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}",
            method="PATCH",
            json={
                "title": title,
                "folder_id": folder_id,
                "archived": archived,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Document,
                    parse_obj_as(
                        type_=Document,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_document_translation(
        self,
        document_id: DocumentId,
        *,
        target_language: typing.Optional[DocumentTranslationTargetLanguage] = OMIT,
        translation_style: typing.Optional[str] = OMIT,
        force: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DocumentTranslationStatus]:
        """
        Start a document translation. Text and transcript documents use paragraph-level
        translation.

        **API price:** USD 0.25 per 1,000 billable words, deducted from your API balance.
        Pricing is prorated to the word: 1,000 billable words costs USD 0.25 and 10,000
        billable words costs USD 2.50. Cached current paragraphs are free; stale, missing,
        failed, forced, or newly added paragraphs are billable.

        Repeated requests for the same document and translation configuration reuse
        cached work and the same billing identity, preventing duplicate charges.

        A document can have multiple translations. Each combination of target language and
        translation style is stored separately, so the same document can be translated
        into both English and Hebrew without duplicating the source document.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        target_language : typing.Optional[DocumentTranslationTargetLanguage]
            Translation target language. Use `en` or `he`; omit it to use automatic
            English/Hebrew direction selection. Custom styles and language-specific
            built-ins require their explicit compatible target language.

        translation_style : typing.Optional[str]
            Translation style ID. Built-ins are `default` for a clear natural translation,
            `learning_english` for polished Torah-learning English, and `sefer_hebrew` for
            traditional sefer-style Hebrew. Custom style IDs come from `/v1/translation-styles`.
            Omit this to use `default`. `learning_english` requires target language `en`,
            `sefer_hebrew` requires `he`, and each custom style declares its compatible language.

        force : typing.Optional[bool]
            Regenerate the translation even if cached content already exists.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DocumentTranslationStatus]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}/translations",
            method="POST",
            json={
                "target_language": target_language,
                "translation_style": translation_style,
                "force": force,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentTranslationStatus,
                    parse_obj_as(
                        type_=DocumentTranslationStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidDocument(headers=dict(_response.headers))
            if _response.status_code == 402:
                raise InsufficientApiBalance(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_document_translation(
        self,
        document_id: DocumentId,
        target_language: DocumentTranslationTargetLanguage,
        *,
        translation_style: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DocumentTranslationStatus]:
        """
        Get the translation for a target language and style, including current status,
        remaining billable words, estimated API cost, and translated content.

        The service rebuilds the document's current paragraphs or pages and compares
        their hashes with the hashes stored during translation. Changed source content
        is returned as stale and becomes billable again when translation is requested.

        Parameters
        ----------
        document_id : DocumentId
            Stable document ID.

        target_language : DocumentTranslationTargetLanguage
            Target language used when the translation was created, or `auto` for automatic direction selection.

        translation_style : typing.Optional[str]
            Translation style ID. Built-ins are `default`, `learning_english` for an
            English target, and `sefer_hebrew` for a Hebrew target. Omit this to use
            `default`. Custom style IDs come from `/v1/translation-styles`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DocumentTranslationStatus]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/documents/{jsonable_encoder(document_id)}/translations/{jsonable_encoder(target_language)}",
            method="GET",
            params={
                "translation_style": translation_style,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DocumentTranslationStatus,
                    parse_obj_as(
                        type_=DocumentTranslationStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise DocumentNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
