# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..transcribe.types.batch_audio_source import BatchAudioSource
from ..transcribe.types.batch_file_content_type import BatchFileContentType
from ..transcribe.types.batch_file_create_from_rss_response import BatchFileCreateFromRssResponse
from ..transcribe.types.batch_file_detail import BatchFileDetail
from ..transcribe.types.batch_file_metadata import BatchFileMetadata
from ..transcribe.types.batch_file_upload_response import BatchFileUploadResponse
from ..transcribe.types.batch_manifest_audio_source import BatchManifestAudioSource
from ..transcribe.types.batch_status_response import BatchStatusResponse
from ..transcribe.types.batch_transcription_request_info import BatchTranscriptionRequestInfo
from ..transcribe.types.batch_transcription_response import BatchTranscriptionResponse
from ..transcribe.types.list_batch_files_response import ListBatchFilesResponse
from ..transcribe.types.processing_mode import ProcessingMode
from ..transcribe.types.transcription_info import TranscriptionInfo
from .raw_client import AsyncRawBatchTranscribeClient, RawBatchTranscribeClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BatchTranscribeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBatchTranscribeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBatchTranscribeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBatchTranscribeClient
        """
        return self._raw_client

    def create_batch_transcription(
        self,
        *,
        info: BatchTranscriptionRequestInfo,
        processing_mode: typing.Optional[ProcessingMode] = OMIT,
        batch_file_id: typing.Optional[uuid.UUID] = OMIT,
        audio_sources: typing.Optional[typing.Sequence[BatchAudioSource]] = OMIT,
        batch_title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchTranscriptionResponse:
        """
        Create multiple transcriptions in a single batch request.

        **Choose a processing mode:**

        - **Express mode**: Submit up to 10 files at once with `audio_sources`. Express batches may take longer than individual transcription requests, but make it easier to submit multiple files together. Pricing for v1 is $1.50/hour.
        - **Standard mode**: Transcriptions processed within 24 hours. Max 500 files. Lower cost. First upload a manifest via [Upload Batch Manifest File](/api-reference/batch-transcribe/upload-batch-file), then pass the `batch_file_id` here. Pricing for v1 batch standard is $1.00/hour. If you need higher limits, contact support@sofer.ai.

        All files in the batch share the same transcription settings (model, language, etc.) defined in `info`.

        Speaker settings can be provided at the batch level or per item. Per-item `num_speakers` or `auto_detect_speakers` settings take precedence over the batch-level speaker settings in `info`. If an item omits both speaker fields, it inherits the batch-level setting. If neither level provides a speaker setting, the transcription defaults to one speaker. Do not provide both `num_speakers` and `auto_detect_speakers` in the same object.

        If you include a `client_item_id` on each item, it must be unique within the batch. You can later resolve a `client_item_id` back to the canonical transcription ID with [Get Batch Transcription By Client Item ID](/api-reference/batch-transcribe/get-batch-transcription-by-client-item-id).

        Parameters
        ----------
        info : BatchTranscriptionRequestInfo
            Transcription settings applied to all files in the batch (model, language, etc.).

            Batch-level speaker settings are defaults. Per-item `num_speakers` or `auto_detect_speakers` settings in `audio_sources` or a batch manifest take precedence for that item.

        processing_mode : typing.Optional[ProcessingMode]
            Choose how the batch is processed:
            - `standard` (default): Lower cost, processed within 24 hours. Max 500 files. Use with `batch_file_id`. Pricing for v1 batch standard is $1.00/hour. If you need higher limits, contact support@sofer.ai.
            - `express`: Submit up to 10 files at once with `audio_sources`. Express batches may take longer than individual transcription requests, but make it easier to submit multiple files together. Pricing for v1 is $1.50/hour.

        batch_file_id : typing.Optional[uuid.UUID]
            **For standard mode only.** ID of a previously uploaded batch manifest.

            Get this by calling [Upload Batch Manifest File](/api-reference/batch-transcribe/upload-batch-file) first.

        audio_sources : typing.Optional[typing.Sequence[BatchAudioSource]]
            **For express mode only.** List of audio URLs to transcribe (max 10).

            Each item needs an `audio_url` and can optionally include a `title`, `client_item_id`, `num_speakers`, or `auto_detect_speakers`.

            Per-item `num_speakers` or `auto_detect_speakers` settings take precedence over the batch-level speaker settings in `info`.

            If you provide `client_item_id`, it must be unique within the batch and can be used later to look up the resulting transcription.

        batch_title : typing.Optional[str]
            Default title prefix for transcriptions. Individual items can override this. Items without titles become "{batch_title} - Item 1", "{batch_title} - Item 2", etc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchTranscriptionResponse
            Returns the batch ID and individual transcription IDs. Use [Get Batch Status](/api-reference/batch-transcribe/get-batch-status) to track progress.

        Examples
        --------
        from soferai import SoferAI
        from soferai.transcribe import BatchAudioSource, BatchTranscriptionRequestInfo

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.create_batch_transcription(
            audio_sources=[
                BatchAudioSource(
                    audio_url="https://example.com/audio1.mp3",
                    title="Rabbi Cohen's Shiur on Shabbos",
                    client_item_id="shiur_shabbos",
                ),
                BatchAudioSource(
                    audio_url="https://example.com/audio2.mp3",
                    title="Rabbi Cohen's Shiur on Kashrus",
                    client_item_id="shiur_kashrus",
                ),
            ],
            info=BatchTranscriptionRequestInfo(
                model="v1",
                primary_language="en",
                hebrew_word_format=["en", "he"],
                num_speakers=1,
            ),
            batch_title="Rabbi Cohen Shiurim",
            processing_mode="express",
        )
        """
        _response = self._raw_client.create_batch_transcription(
            info=info,
            processing_mode=processing_mode,
            batch_file_id=batch_file_id,
            audio_sources=audio_sources,
            batch_title=batch_title,
            request_options=request_options,
        )
        return _response.data

    def upload_batch_file(
        self,
        *,
        content_type: BatchFileContentType,
        json_items: typing.Optional[typing.Sequence[BatchManifestAudioSource]] = OMIT,
        jsonl: typing.Optional[str] = OMIT,
        metadata: typing.Optional[BatchFileMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchFileUploadResponse:
        """
        Upload a batch manifest containing audio URLs for standard mode batch processing.

        **Workflow:**
        1. Upload your manifest here to get a `batch_file_id`
        2. Use that ID in [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription) with `processing_mode: "standard"`

        The manifest is a list of audio sources (max 500), each with a URL and optional title or `client_item_id`. If you provide `client_item_id`, it must be unique within the manifest. You can provide it as a JSON array or JSONL format. If you need higher limits, contact support@sofer.ai.

        Parameters
        ----------
        content_type : BatchFileContentType
            Format of your manifest data

        json_items : typing.Optional[typing.Sequence[BatchManifestAudioSource]]
            **For JSON format.** Array of audio sources to transcribe (max 500). If you need higher limits, contact support@sofer.ai.

        jsonl : typing.Optional[str]
            **For JSONL format.** One audio source per line as JSON, separated by newlines (max 500 lines). If you need higher limits, contact support@sofer.ai.

            Example: `{"audio_url": "https://..."}\n{"audio_url": "https://..."}`

        metadata : typing.Optional[BatchFileMetadata]
            Optional title and description for this manifest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileUploadResponse

        Examples
        --------
        from soferai import SoferAI
        from soferai.transcribe import BatchFileMetadata, BatchManifestAudioSource

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.upload_batch_file(
            content_type="json",
            json_items=[
                BatchManifestAudioSource(
                    audio_url="https://example.com/shiur1.mp3",
                    title="Parshas Bereishis - Rabbi Cohen",
                    client_item_id="bereishis",
                ),
                BatchManifestAudioSource(
                    audio_url="https://example.com/shiur2.mp3",
                    title="Parshas Noach - Rabbi Cohen",
                    client_item_id="noach",
                ),
                BatchManifestAudioSource(
                    audio_url="https://example.com/shiur3.mp3",
                    title="Parshas Lech Lecha - Rabbi Cohen",
                    client_item_id="lech_lecha",
                ),
            ],
            metadata=BatchFileMetadata(
                title="Rabbi Cohen Weekly Parsha Series",
                description="Shiurim from Fall 2024",
            ),
        )
        """
        _response = self._raw_client.upload_batch_file(
            content_type=content_type,
            json_items=json_items,
            jsonl=jsonl,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def create_batch_file_from_rss(
        self,
        *,
        rss_url: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        metadata: typing.Optional[BatchFileMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchFileCreateFromRssResponse:
        """
        Create a standard-mode batch manifest from a podcast RSS feed.

        The feed is fetched and parsed for podcast episode audio enclosures. Each episode with an audio enclosure becomes one manifest item with `audio_url`, title, and a stable `client_item_id`. The returned `batch_file_id` can be used in [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription) with `processing_mode: "standard"`.

        By default, this imports up to the standard batch manifest limit. Use `limit` to import fewer episodes. If the feed has more episodes than one manifest can hold, call this endpoint again with the previous response's `next_offset`.

        Need to find the RSS URL for a podcast? Try the [RSS.com Podcast RSS Feed Finder](https://rss.com/tools/find-my-feed/) and use the feed URL it returns.

        Parameters
        ----------
        rss_url : str
            Public RSS feed URL to fetch and parse for podcast episode audio enclosures.

        limit : typing.Optional[int]
            Optional maximum number of episodes to import. Defaults to the standard batch manifest limit.

        offset : typing.Optional[int]
            Number of podcast episode audio enclosures to skip before importing. Use `next_offset` from the previous response to fetch the next page.

        metadata : typing.Optional[BatchFileMetadata]
            Optional title and description for this manifest. If omitted, the podcast title from the feed is used when available.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileCreateFromRssResponse

        Examples
        --------
        from soferai import SoferAI
        from soferai.transcribe import BatchFileMetadata

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.create_batch_file_from_rss(
            rss_url="https://example.com/podcast/feed.xml",
            limit=100,
            offset=0,
            metadata=BatchFileMetadata(
                title="Weekly Parsha Podcast",
                description="Imported from RSS",
            ),
        )
        """
        _response = self._raw_client.create_batch_file_from_rss(
            rss_url=rss_url, limit=limit, offset=offset, metadata=metadata, request_options=request_options
        )
        return _response.data

    def list_batch_files(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListBatchFilesResponse:
        """
        List all batch file manifests you've uploaded. Use this to find a `batch_file_id` for starting a standard mode batch.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBatchFilesResponse

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.list_batch_files()
        """
        _response = self._raw_client.list_batch_files(request_options=request_options)
        return _response.data

    def get_batch_file(
        self, batch_file_id: uuid.UUID, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchFileDetail:
        """
        Get details about a specific batch file manifest, including its validation status. Check this after uploading to ensure your manifest is valid before starting a batch.

        Parameters
        ----------
        batch_file_id : uuid.UUID
            The batch file ID returned from [Upload Batch File](/api-reference/batch-transcribe/upload-batch-file)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileDetail

        Examples
        --------
        import uuid

        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.get_batch_file(
            batch_file_id=uuid.UUID(
                "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            ),
        )
        """
        _response = self._raw_client.get_batch_file(batch_file_id, request_options=request_options)
        return _response.data

    def get_batch_status(
        self, batch_id: uuid.UUID, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchStatusResponse:
        """
        Check the progress of a batch transcription. Returns counts of completed, failed, and pending transcriptions, plus details for each individual transcription.

        If a batch item was submitted with `client_item_id`, that value is echoed back in each transcription entry.

        Parameters
        ----------
        batch_id : uuid.UUID
            The batch ID returned from [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchStatusResponse

        Examples
        --------
        import uuid

        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.get_batch_status(
            batch_id=uuid.UUID(
                "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            ),
        )
        """
        _response = self._raw_client.get_batch_status(batch_id, request_options=request_options)
        return _response.data

    def get_batch_transcription_by_client_item_id(
        self, batch_id: uuid.UUID, *, client_item_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TranscriptionInfo:
        """
        Resolve a batch item's `client_item_id` to the resulting transcription.

        `client_item_id` values are unique only within a batch, so this lookup is scoped by `batch_id`.

        The response is a standard [TranscriptionInfo](/api-reference/transcribe/get-transcription-status) object. Its `id` field is the canonical transcription ID for the batch item.

        Parameters
        ----------
        batch_id : uuid.UUID
            The batch ID returned from [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription)

        client_item_id : str
            The caller-defined client_item_id to resolve within this batch.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranscriptionInfo

        Examples
        --------
        import uuid

        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.batch_transcribe.get_batch_transcription_by_client_item_id(
            batch_id=uuid.UUID(
                "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            ),
            client_item_id="shiur_1",
        )
        """
        _response = self._raw_client.get_batch_transcription_by_client_item_id(
            batch_id, client_item_id=client_item_id, request_options=request_options
        )
        return _response.data


class AsyncBatchTranscribeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBatchTranscribeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBatchTranscribeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBatchTranscribeClient
        """
        return self._raw_client

    async def create_batch_transcription(
        self,
        *,
        info: BatchTranscriptionRequestInfo,
        processing_mode: typing.Optional[ProcessingMode] = OMIT,
        batch_file_id: typing.Optional[uuid.UUID] = OMIT,
        audio_sources: typing.Optional[typing.Sequence[BatchAudioSource]] = OMIT,
        batch_title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchTranscriptionResponse:
        """
        Create multiple transcriptions in a single batch request.

        **Choose a processing mode:**

        - **Express mode**: Submit up to 10 files at once with `audio_sources`. Express batches may take longer than individual transcription requests, but make it easier to submit multiple files together. Pricing for v1 is $1.50/hour.
        - **Standard mode**: Transcriptions processed within 24 hours. Max 500 files. Lower cost. First upload a manifest via [Upload Batch Manifest File](/api-reference/batch-transcribe/upload-batch-file), then pass the `batch_file_id` here. Pricing for v1 batch standard is $1.00/hour. If you need higher limits, contact support@sofer.ai.

        All files in the batch share the same transcription settings (model, language, etc.) defined in `info`.

        Speaker settings can be provided at the batch level or per item. Per-item `num_speakers` or `auto_detect_speakers` settings take precedence over the batch-level speaker settings in `info`. If an item omits both speaker fields, it inherits the batch-level setting. If neither level provides a speaker setting, the transcription defaults to one speaker. Do not provide both `num_speakers` and `auto_detect_speakers` in the same object.

        If you include a `client_item_id` on each item, it must be unique within the batch. You can later resolve a `client_item_id` back to the canonical transcription ID with [Get Batch Transcription By Client Item ID](/api-reference/batch-transcribe/get-batch-transcription-by-client-item-id).

        Parameters
        ----------
        info : BatchTranscriptionRequestInfo
            Transcription settings applied to all files in the batch (model, language, etc.).

            Batch-level speaker settings are defaults. Per-item `num_speakers` or `auto_detect_speakers` settings in `audio_sources` or a batch manifest take precedence for that item.

        processing_mode : typing.Optional[ProcessingMode]
            Choose how the batch is processed:
            - `standard` (default): Lower cost, processed within 24 hours. Max 500 files. Use with `batch_file_id`. Pricing for v1 batch standard is $1.00/hour. If you need higher limits, contact support@sofer.ai.
            - `express`: Submit up to 10 files at once with `audio_sources`. Express batches may take longer than individual transcription requests, but make it easier to submit multiple files together. Pricing for v1 is $1.50/hour.

        batch_file_id : typing.Optional[uuid.UUID]
            **For standard mode only.** ID of a previously uploaded batch manifest.

            Get this by calling [Upload Batch Manifest File](/api-reference/batch-transcribe/upload-batch-file) first.

        audio_sources : typing.Optional[typing.Sequence[BatchAudioSource]]
            **For express mode only.** List of audio URLs to transcribe (max 10).

            Each item needs an `audio_url` and can optionally include a `title`, `client_item_id`, `num_speakers`, or `auto_detect_speakers`.

            Per-item `num_speakers` or `auto_detect_speakers` settings take precedence over the batch-level speaker settings in `info`.

            If you provide `client_item_id`, it must be unique within the batch and can be used later to look up the resulting transcription.

        batch_title : typing.Optional[str]
            Default title prefix for transcriptions. Individual items can override this. Items without titles become "{batch_title} - Item 1", "{batch_title} - Item 2", etc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchTranscriptionResponse
            Returns the batch ID and individual transcription IDs. Use [Get Batch Status](/api-reference/batch-transcribe/get-batch-status) to track progress.

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI
        from soferai.transcribe import BatchAudioSource, BatchTranscriptionRequestInfo

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.create_batch_transcription(
                audio_sources=[
                    BatchAudioSource(
                        audio_url="https://example.com/audio1.mp3",
                        title="Rabbi Cohen's Shiur on Shabbos",
                        client_item_id="shiur_shabbos",
                    ),
                    BatchAudioSource(
                        audio_url="https://example.com/audio2.mp3",
                        title="Rabbi Cohen's Shiur on Kashrus",
                        client_item_id="shiur_kashrus",
                    ),
                ],
                info=BatchTranscriptionRequestInfo(
                    model="v1",
                    primary_language="en",
                    hebrew_word_format=["en", "he"],
                    num_speakers=1,
                ),
                batch_title="Rabbi Cohen Shiurim",
                processing_mode="express",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_batch_transcription(
            info=info,
            processing_mode=processing_mode,
            batch_file_id=batch_file_id,
            audio_sources=audio_sources,
            batch_title=batch_title,
            request_options=request_options,
        )
        return _response.data

    async def upload_batch_file(
        self,
        *,
        content_type: BatchFileContentType,
        json_items: typing.Optional[typing.Sequence[BatchManifestAudioSource]] = OMIT,
        jsonl: typing.Optional[str] = OMIT,
        metadata: typing.Optional[BatchFileMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchFileUploadResponse:
        """
        Upload a batch manifest containing audio URLs for standard mode batch processing.

        **Workflow:**
        1. Upload your manifest here to get a `batch_file_id`
        2. Use that ID in [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription) with `processing_mode: "standard"`

        The manifest is a list of audio sources (max 500), each with a URL and optional title or `client_item_id`. If you provide `client_item_id`, it must be unique within the manifest. You can provide it as a JSON array or JSONL format. If you need higher limits, contact support@sofer.ai.

        Parameters
        ----------
        content_type : BatchFileContentType
            Format of your manifest data

        json_items : typing.Optional[typing.Sequence[BatchManifestAudioSource]]
            **For JSON format.** Array of audio sources to transcribe (max 500). If you need higher limits, contact support@sofer.ai.

        jsonl : typing.Optional[str]
            **For JSONL format.** One audio source per line as JSON, separated by newlines (max 500 lines). If you need higher limits, contact support@sofer.ai.

            Example: `{"audio_url": "https://..."}\n{"audio_url": "https://..."}`

        metadata : typing.Optional[BatchFileMetadata]
            Optional title and description for this manifest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileUploadResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI
        from soferai.transcribe import BatchFileMetadata, BatchManifestAudioSource

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.upload_batch_file(
                content_type="json",
                json_items=[
                    BatchManifestAudioSource(
                        audio_url="https://example.com/shiur1.mp3",
                        title="Parshas Bereishis - Rabbi Cohen",
                        client_item_id="bereishis",
                    ),
                    BatchManifestAudioSource(
                        audio_url="https://example.com/shiur2.mp3",
                        title="Parshas Noach - Rabbi Cohen",
                        client_item_id="noach",
                    ),
                    BatchManifestAudioSource(
                        audio_url="https://example.com/shiur3.mp3",
                        title="Parshas Lech Lecha - Rabbi Cohen",
                        client_item_id="lech_lecha",
                    ),
                ],
                metadata=BatchFileMetadata(
                    title="Rabbi Cohen Weekly Parsha Series",
                    description="Shiurim from Fall 2024",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_batch_file(
            content_type=content_type,
            json_items=json_items,
            jsonl=jsonl,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def create_batch_file_from_rss(
        self,
        *,
        rss_url: str,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        metadata: typing.Optional[BatchFileMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchFileCreateFromRssResponse:
        """
        Create a standard-mode batch manifest from a podcast RSS feed.

        The feed is fetched and parsed for podcast episode audio enclosures. Each episode with an audio enclosure becomes one manifest item with `audio_url`, title, and a stable `client_item_id`. The returned `batch_file_id` can be used in [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription) with `processing_mode: "standard"`.

        By default, this imports up to the standard batch manifest limit. Use `limit` to import fewer episodes. If the feed has more episodes than one manifest can hold, call this endpoint again with the previous response's `next_offset`.

        Need to find the RSS URL for a podcast? Try the [RSS.com Podcast RSS Feed Finder](https://rss.com/tools/find-my-feed/) and use the feed URL it returns.

        Parameters
        ----------
        rss_url : str
            Public RSS feed URL to fetch and parse for podcast episode audio enclosures.

        limit : typing.Optional[int]
            Optional maximum number of episodes to import. Defaults to the standard batch manifest limit.

        offset : typing.Optional[int]
            Number of podcast episode audio enclosures to skip before importing. Use `next_offset` from the previous response to fetch the next page.

        metadata : typing.Optional[BatchFileMetadata]
            Optional title and description for this manifest. If omitted, the podcast title from the feed is used when available.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileCreateFromRssResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI
        from soferai.transcribe import BatchFileMetadata

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.create_batch_file_from_rss(
                rss_url="https://example.com/podcast/feed.xml",
                limit=100,
                offset=0,
                metadata=BatchFileMetadata(
                    title="Weekly Parsha Podcast",
                    description="Imported from RSS",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_batch_file_from_rss(
            rss_url=rss_url, limit=limit, offset=offset, metadata=metadata, request_options=request_options
        )
        return _response.data

    async def list_batch_files(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListBatchFilesResponse:
        """
        List all batch file manifests you've uploaded. Use this to find a `batch_file_id` for starting a standard mode batch.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBatchFilesResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.list_batch_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_batch_files(request_options=request_options)
        return _response.data

    async def get_batch_file(
        self, batch_file_id: uuid.UUID, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchFileDetail:
        """
        Get details about a specific batch file manifest, including its validation status. Check this after uploading to ensure your manifest is valid before starting a batch.

        Parameters
        ----------
        batch_file_id : uuid.UUID
            The batch file ID returned from [Upload Batch File](/api-reference/batch-transcribe/upload-batch-file)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchFileDetail

        Examples
        --------
        import asyncio
        import uuid

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.get_batch_file(
                batch_file_id=uuid.UUID(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_batch_file(batch_file_id, request_options=request_options)
        return _response.data

    async def get_batch_status(
        self, batch_id: uuid.UUID, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchStatusResponse:
        """
        Check the progress of a batch transcription. Returns counts of completed, failed, and pending transcriptions, plus details for each individual transcription.

        If a batch item was submitted with `client_item_id`, that value is echoed back in each transcription entry.

        Parameters
        ----------
        batch_id : uuid.UUID
            The batch ID returned from [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchStatusResponse

        Examples
        --------
        import asyncio
        import uuid

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.get_batch_status(
                batch_id=uuid.UUID(
                    "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_batch_status(batch_id, request_options=request_options)
        return _response.data

    async def get_batch_transcription_by_client_item_id(
        self, batch_id: uuid.UUID, *, client_item_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TranscriptionInfo:
        """
        Resolve a batch item's `client_item_id` to the resulting transcription.

        `client_item_id` values are unique only within a batch, so this lookup is scoped by `batch_id`.

        The response is a standard [TranscriptionInfo](/api-reference/transcribe/get-transcription-status) object. Its `id` field is the canonical transcription ID for the batch item.

        Parameters
        ----------
        batch_id : uuid.UUID
            The batch ID returned from [Create Batch Transcription](/api-reference/batch-transcribe/create-batch-transcription)

        client_item_id : str
            The caller-defined client_item_id to resolve within this batch.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranscriptionInfo

        Examples
        --------
        import asyncio
        import uuid

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.batch_transcribe.get_batch_transcription_by_client_item_id(
                batch_id=uuid.UUID(
                    "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                ),
                client_item_id="shiur_1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_batch_transcription_by_client_item_id(
            batch_id, client_item_id=client_item_id, request_options=request_options
        )
        return _response.data
