# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMaishivClient, RawMaishivClient
from .types.add_knowledge_base_document_response import AddKnowledgeBaseDocumentResponse
from .types.knowledge_base_search_chunk import KnowledgeBaseSearchChunk
from .types.remove_knowledge_base_document_response import RemoveKnowledgeBaseDocumentResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MaishivClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMaishivClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMaishivClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMaishivClient
        """
        return self._raw_client

    def add_to_knowledge_base(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AddKnowledgeBaseDocumentResponse:
        """
        Add an owned document to the user's knowledge base, shared with the website.
        All accounts can add unlimited documents; website subscription tiers do not
        impose a knowledge-base file-count limit. API retrievals are billed separately.

        Parameters
        ----------
        document_id : str
            ID of the document to add to the knowledge base.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddKnowledgeBaseDocumentResponse

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.maishiv.add_to_knowledge_base(
            document_id="document_id",
        )
        """
        _response = self._raw_client.add_to_knowledge_base(document_id=document_id, request_options=request_options)
        return _response.data

    def list_knowledge_base_docs(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[str]:
        """
        Get all document IDs currently in the knowledge base.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.maishiv.list_knowledge_base_docs()
        """
        _response = self._raw_client.list_knowledge_base_docs(request_options=request_options)
        return _response.data

    def search_knowledge_base_chunks(
        self, *, query: str, n: typing.Optional[int] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[KnowledgeBaseSearchChunk]:
        """
        Retrieve up to n passages from the authenticated user's Maishiv knowledge base,
        without generating an answer. Only owned documents are returned. Times are
        nullable seconds and are provided only for a unique, reliable audio alignment.
        Each completed search costs $0.01 from the user's prepaid API balance,
        regardless of n or the number of matches. Zero-match searches are billable.
        Invalid requests, missing knowledge bases, and failed searches are not charged.
        Website subscriptions and daily question allowances do not apply.

        Parameters
        ----------
        query : str
            Search query, trimmed before use; must contain 1 to 8000 characters after trimming.

        n : typing.Optional[int]
            Maximum passages to return; an integer from 1 to 50. Defaults to 10 when omitted or null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[KnowledgeBaseSearchChunk]

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.maishiv.search_knowledge_base_chunks(
            query="query",
        )
        """
        _response = self._raw_client.search_knowledge_base_chunks(query=query, n=n, request_options=request_options)
        return _response.data

    def remove_from_knowledge_base(
        self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RemoveKnowledgeBaseDocumentResponse:
        """
        Remove a document from the knowledge base.

        Parameters
        ----------
        document_id : str
            ID of the document to remove from the knowledge base.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveKnowledgeBaseDocumentResponse

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.maishiv.remove_from_knowledge_base(
            document_id="document_id",
        )
        """
        _response = self._raw_client.remove_from_knowledge_base(document_id, request_options=request_options)
        return _response.data


class AsyncMaishivClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMaishivClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMaishivClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMaishivClient
        """
        return self._raw_client

    async def add_to_knowledge_base(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AddKnowledgeBaseDocumentResponse:
        """
        Add an owned document to the user's knowledge base, shared with the website.
        All accounts can add unlimited documents; website subscription tiers do not
        impose a knowledge-base file-count limit. API retrievals are billed separately.

        Parameters
        ----------
        document_id : str
            ID of the document to add to the knowledge base.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddKnowledgeBaseDocumentResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.maishiv.add_to_knowledge_base(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_to_knowledge_base(
            document_id=document_id, request_options=request_options
        )
        return _response.data

    async def list_knowledge_base_docs(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[str]:
        """
        Get all document IDs currently in the knowledge base.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[str]

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.maishiv.list_knowledge_base_docs()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_knowledge_base_docs(request_options=request_options)
        return _response.data

    async def search_knowledge_base_chunks(
        self, *, query: str, n: typing.Optional[int] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[KnowledgeBaseSearchChunk]:
        """
        Retrieve up to n passages from the authenticated user's Maishiv knowledge base,
        without generating an answer. Only owned documents are returned. Times are
        nullable seconds and are provided only for a unique, reliable audio alignment.
        Each completed search costs $0.01 from the user's prepaid API balance,
        regardless of n or the number of matches. Zero-match searches are billable.
        Invalid requests, missing knowledge bases, and failed searches are not charged.
        Website subscriptions and daily question allowances do not apply.

        Parameters
        ----------
        query : str
            Search query, trimmed before use; must contain 1 to 8000 characters after trimming.

        n : typing.Optional[int]
            Maximum passages to return; an integer from 1 to 50. Defaults to 10 when omitted or null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[KnowledgeBaseSearchChunk]

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.maishiv.search_knowledge_base_chunks(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_knowledge_base_chunks(
            query=query, n=n, request_options=request_options
        )
        return _response.data

    async def remove_from_knowledge_base(
        self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RemoveKnowledgeBaseDocumentResponse:
        """
        Remove a document from the knowledge base.

        Parameters
        ----------
        document_id : str
            ID of the document to remove from the knowledge base.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RemoveKnowledgeBaseDocumentResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.maishiv.remove_from_knowledge_base(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_from_knowledge_base(document_id, request_options=request_options)
        return _response.data
