# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..transcribe.errors.authentication_error import AuthenticationError
from ..transcribe.errors.rate_limit_error import RateLimitError
from .types.duration_response import DurationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawUtilsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_duration(
        self,
        *,
        audio_url: typing.Optional[str] = OMIT,
        audio_file: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DurationResponse]:
        """
        Returns the audio duration in seconds for a provided URL or base64-encoded file.

        Provide either `audio_url` or `audio_file` (base64). If both are provided, the request is invalid.

        Parameters
        ----------
        audio_url : typing.Optional[str]
            Direct URL to a downloadable audio file.

        audio_file : typing.Optional[str]
            Base64-encoded audio file content. Do not include a data URI prefix.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DurationResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/utils/duration",
            method="POST",
            json={
                "audio_url": audio_url,
                "audio_file": audio_file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DurationResponse,
                    parse_obj_as(
                        type_=DurationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawUtilsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_duration(
        self,
        *,
        audio_url: typing.Optional[str] = OMIT,
        audio_file: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DurationResponse]:
        """
        Returns the audio duration in seconds for a provided URL or base64-encoded file.

        Provide either `audio_url` or `audio_file` (base64). If both are provided, the request is invalid.

        Parameters
        ----------
        audio_url : typing.Optional[str]
            Direct URL to a downloadable audio file.

        audio_file : typing.Optional[str]
            Base64-encoded audio file content. Do not include a data URI prefix.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DurationResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/utils/duration",
            method="POST",
            json={
                "audio_url": audio_url,
                "audio_file": audio_file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DurationResponse,
                    parse_obj_as(
                        type_=DurationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
