# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ...core.pydantic_utilities import UniversalBaseModel
from .title_update_mode import TitleUpdateMode


class AutoGenerateTitleRequest(UniversalBaseModel):
    mode: typing.Optional[TitleUpdateMode] = pydantic.Field(default=None)
    """
    Whether to replace the current title or append the generated title to it.
    """

    separator: typing.Optional[str] = pydantic.Field(default=None)
    """
    Separator used between the existing title and generated title when mode is append.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
