# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .title_update_mode import TitleUpdateMode


class AutoGenerateTitleResponse(UniversalBaseModel):
    transcription_id: uuid.UUID = pydantic.Field()
    """
    ID of the updated transcription.
    """

    mode: TitleUpdateMode = pydantic.Field()
    """
    How the generated title was applied.
    """

    previous_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title before generation.
    """

    generated_title: str = pydantic.Field()
    """
    Title generated from the transcript text.
    """

    title: str = pydantic.Field()
    """
    Final title saved to the transcription.
    """

    model: str = pydantic.Field()
    """
    Gemini model used to generate the title.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
