# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing


class AudioChunk(UniversalBaseModel):
    data: str = pydantic.Field()
    """
    Base64-encoded audio data
    """

    mime_type: str = pydantic.Field()
    """
    MIME type of the audio data (e.g., "audio/pcm", "audio/wav")
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
