# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class UpdateCategoryRequest(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    New name for the category
    """

    color_hex: typing.Optional[str] = pydantic.Field(default=None)
    """
    New hex color code for the category (e.g.,
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    New description for the category
    """

    auto_tag_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to automatically tag transcripts that match this category
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
