# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .translation_style_kind import TranslationStyleKind
from .translation_style_target_language import TranslationStyleTargetLanguage


class TranslationStyle(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Value to pass as `translation_style` when creating a translation.
    """

    name: str = pydantic.Field()
    """
    Display name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short description of the style.
    """

    target_languages: typing.List[TranslationStyleTargetLanguage] = pydantic.Field()
    """
    Languages this style can be used with.
    """

    kind: TranslationStyleKind = pydantic.Field()
    """
    Whether this is a built-in or user-created style.
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    The authenticated user's custom style instructions. Omitted for built-in styles.
    """

    verified: bool = pydantic.Field()
    """
    Whether the style instructions passed safety and scope validation.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Creation time for a custom style.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Last update time for a custom style.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
