# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class TranslationStyleUpdateRequest(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    New display name. Omit to leave unchanged.
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Replacement style-only instructions. Omit to leave unchanged.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
