# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class TranslationStyleDeleteResponse(UniversalBaseModel):
    deleted: bool = pydantic.Field()
    """
    True when the custom style was deleted.
    """

    translation_style_id: str = pydantic.Field()
    """
    Deleted custom translation style ID.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
