# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawTranslationStylesClient, RawTranslationStylesClient
from .types.translation_style import TranslationStyle
from .types.translation_style_delete_response import TranslationStyleDeleteResponse
from .types.translation_style_list_response import TranslationStyleListResponse
from .types.translation_style_target_language import TranslationStyleTargetLanguage

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TranslationStylesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTranslationStylesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTranslationStylesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTranslationStylesClient
        """
        return self._raw_client

    def list_translation_styles(
        self,
        *,
        target_language: typing.Optional[TranslationStyleTargetLanguage] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyleListResponse:
        """
        List the built-in translation styles and the authenticated API user's custom
        styles. Optionally filter the result by a compatible target language.

        Parameters
        ----------
        target_language : typing.Optional[TranslationStyleTargetLanguage]
            Return only styles compatible with this target language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyleListResponse

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.translation_styles.list_translation_styles()
        """
        _response = self._raw_client.list_translation_styles(
            target_language=target_language, request_options=request_options
        )
        return _response.data

    def create_translation_style(
        self,
        *,
        name: str,
        target_language: TranslationStyleTargetLanguage,
        instructions: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyle:
        """
        Create a reusable custom translation style. The instructions are safety-validated
        and must only describe translation wording, tone, register, terminology,
        transliteration, quote handling, or similar style choices. Instructions cannot
        override the target language, change document structure, summarize, add content,
        select a model, or alter output-format and safety rules.

        Use the returned `id` directly as `translation_style` when creating a translation.

        Parameters
        ----------
        name : str
            Display name, up to 60 characters.

        target_language : TranslationStyleTargetLanguage
            Language translations using this style will produce.

        instructions : str
            Style-only instructions, up to 4,000 characters. HTML is not accepted; use paired asterisks for emphasis.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.translation_styles.create_translation_style(
            name="name",
            target_language="en",
            instructions="instructions",
        )
        """
        _response = self._raw_client.create_translation_style(
            name=name, target_language=target_language, instructions=instructions, request_options=request_options
        )
        return _response.data

    def get_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TranslationStyle:
        """
        Retrieve a built-in style or an owned custom translation style.

        Parameters
        ----------
        translation_style_id : str
            Built-in or custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.translation_styles.get_translation_style(
            translation_style_id="translation_style_id",
        )
        """
        _response = self._raw_client.get_translation_style(translation_style_id, request_options=request_options)
        return _response.data

    def update_translation_style(
        self,
        translation_style_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyle:
        """
        Rename an owned custom style or replace its instructions. Changed instructions
        are safety-validated again and invalidate translations cached under this style.
        Built-in styles cannot be modified, and a custom style's target language is immutable.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        instructions : typing.Optional[str]
            Replacement style-only instructions. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.translation_styles.update_translation_style(
            translation_style_id="translation_style_id",
        )
        """
        _response = self._raw_client.update_translation_style(
            translation_style_id, name=name, instructions=instructions, request_options=request_options
        )
        return _response.data

    def delete_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TranslationStyleDeleteResponse:
        """
        Delete an owned custom translation style. Built-in styles cannot be deleted.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyleDeleteResponse

        Examples
        --------
        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.translation_styles.delete_translation_style(
            translation_style_id="translation_style_id",
        )
        """
        _response = self._raw_client.delete_translation_style(translation_style_id, request_options=request_options)
        return _response.data


class AsyncTranslationStylesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTranslationStylesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTranslationStylesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTranslationStylesClient
        """
        return self._raw_client

    async def list_translation_styles(
        self,
        *,
        target_language: typing.Optional[TranslationStyleTargetLanguage] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyleListResponse:
        """
        List the built-in translation styles and the authenticated API user's custom
        styles. Optionally filter the result by a compatible target language.

        Parameters
        ----------
        target_language : typing.Optional[TranslationStyleTargetLanguage]
            Return only styles compatible with this target language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyleListResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.translation_styles.list_translation_styles()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_translation_styles(
            target_language=target_language, request_options=request_options
        )
        return _response.data

    async def create_translation_style(
        self,
        *,
        name: str,
        target_language: TranslationStyleTargetLanguage,
        instructions: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyle:
        """
        Create a reusable custom translation style. The instructions are safety-validated
        and must only describe translation wording, tone, register, terminology,
        transliteration, quote handling, or similar style choices. Instructions cannot
        override the target language, change document structure, summarize, add content,
        select a model, or alter output-format and safety rules.

        Use the returned `id` directly as `translation_style` when creating a translation.

        Parameters
        ----------
        name : str
            Display name, up to 60 characters.

        target_language : TranslationStyleTargetLanguage
            Language translations using this style will produce.

        instructions : str
            Style-only instructions, up to 4,000 characters. HTML is not accepted; use paired asterisks for emphasis.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.translation_styles.create_translation_style(
                name="name",
                target_language="en",
                instructions="instructions",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_translation_style(
            name=name, target_language=target_language, instructions=instructions, request_options=request_options
        )
        return _response.data

    async def get_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TranslationStyle:
        """
        Retrieve a built-in style or an owned custom translation style.

        Parameters
        ----------
        translation_style_id : str
            Built-in or custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.translation_styles.get_translation_style(
                translation_style_id="translation_style_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_translation_style(translation_style_id, request_options=request_options)
        return _response.data

    async def update_translation_style(
        self,
        translation_style_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TranslationStyle:
        """
        Rename an owned custom style or replace its instructions. Changed instructions
        are safety-validated again and invalidate translations cached under this style.
        Built-in styles cannot be modified, and a custom style's target language is immutable.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        instructions : typing.Optional[str]
            Replacement style-only instructions. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyle

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.translation_styles.update_translation_style(
                translation_style_id="translation_style_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_translation_style(
            translation_style_id, name=name, instructions=instructions, request_options=request_options
        )
        return _response.data

    async def delete_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TranslationStyleDeleteResponse:
        """
        Delete an owned custom translation style. Built-in styles cannot be deleted.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranslationStyleDeleteResponse

        Examples
        --------
        import asyncio

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.translation_styles.delete_translation_style(
                translation_style_id="translation_style_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_translation_style(
            translation_style_id, request_options=request_options
        )
        return _response.data
