# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..transcribe.errors.authentication_error import AuthenticationError
from ..transcribe.errors.rate_limit_error import RateLimitError
from .errors.invalid_translation_style import InvalidTranslationStyle
from .errors.translation_style_not_found import TranslationStyleNotFound
from .errors.translation_style_validation_unavailable import TranslationStyleValidationUnavailable
from .types.translation_style import TranslationStyle
from .types.translation_style_delete_response import TranslationStyleDeleteResponse
from .types.translation_style_list_response import TranslationStyleListResponse
from .types.translation_style_target_language import TranslationStyleTargetLanguage

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTranslationStylesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_translation_styles(
        self,
        *,
        target_language: typing.Optional[TranslationStyleTargetLanguage] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TranslationStyleListResponse]:
        """
        List the built-in translation styles and the authenticated API user's custom
        styles. Optionally filter the result by a compatible target language.

        Parameters
        ----------
        target_language : typing.Optional[TranslationStyleTargetLanguage]
            Return only styles compatible with this target language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TranslationStyleListResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/translation-styles/",
            method="GET",
            params={
                "target_language": target_language,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyleListResponse,
                    parse_obj_as(
                        type_=TranslationStyleListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_translation_style(
        self,
        *,
        name: str,
        target_language: TranslationStyleTargetLanguage,
        instructions: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TranslationStyle]:
        """
        Create a reusable custom translation style. The instructions are safety-validated
        and must only describe translation wording, tone, register, terminology,
        transliteration, quote handling, or similar style choices. Instructions cannot
        override the target language, change document structure, summarize, add content,
        select a model, or alter output-format and safety rules.

        Use the returned `id` directly as `translation_style` when creating a translation.

        Parameters
        ----------
        name : str
            Display name, up to 60 characters.

        target_language : TranslationStyleTargetLanguage
            Language translations using this style will produce.

        instructions : str
            Style-only instructions, up to 4,000 characters. HTML is not accepted; use paired asterisks for emphasis.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TranslationStyle]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/translation-styles/",
            method="POST",
            json={
                "name": name,
                "target_language": target_language,
                "instructions": instructions,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 503:
                raise TranslationStyleValidationUnavailable(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[TranslationStyle]:
        """
        Retrieve a built-in style or an owned custom translation style.

        Parameters
        ----------
        translation_style_id : str
            Built-in or custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TranslationStyle]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_translation_style(
        self,
        translation_style_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TranslationStyle]:
        """
        Rename an owned custom style or replace its instructions. Changed instructions
        are safety-validated again and invalidate translations cached under this style.
        Built-in styles cannot be modified, and a custom style's target language is immutable.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        instructions : typing.Optional[str]
            Replacement style-only instructions. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TranslationStyle]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="PATCH",
            json={
                "name": name,
                "instructions": instructions,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 503:
                raise TranslationStyleValidationUnavailable(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[TranslationStyleDeleteResponse]:
        """
        Delete an owned custom translation style. Built-in styles cannot be deleted.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TranslationStyleDeleteResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyleDeleteResponse,
                    parse_obj_as(
                        type_=TranslationStyleDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTranslationStylesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_translation_styles(
        self,
        *,
        target_language: typing.Optional[TranslationStyleTargetLanguage] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TranslationStyleListResponse]:
        """
        List the built-in translation styles and the authenticated API user's custom
        styles. Optionally filter the result by a compatible target language.

        Parameters
        ----------
        target_language : typing.Optional[TranslationStyleTargetLanguage]
            Return only styles compatible with this target language.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TranslationStyleListResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/translation-styles/",
            method="GET",
            params={
                "target_language": target_language,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyleListResponse,
                    parse_obj_as(
                        type_=TranslationStyleListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_translation_style(
        self,
        *,
        name: str,
        target_language: TranslationStyleTargetLanguage,
        instructions: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TranslationStyle]:
        """
        Create a reusable custom translation style. The instructions are safety-validated
        and must only describe translation wording, tone, register, terminology,
        transliteration, quote handling, or similar style choices. Instructions cannot
        override the target language, change document structure, summarize, add content,
        select a model, or alter output-format and safety rules.

        Use the returned `id` directly as `translation_style` when creating a translation.

        Parameters
        ----------
        name : str
            Display name, up to 60 characters.

        target_language : TranslationStyleTargetLanguage
            Language translations using this style will produce.

        instructions : str
            Style-only instructions, up to 4,000 characters. HTML is not accepted; use paired asterisks for emphasis.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TranslationStyle]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/translation-styles/",
            method="POST",
            json={
                "name": name,
                "target_language": target_language,
                "instructions": instructions,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 503:
                raise TranslationStyleValidationUnavailable(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[TranslationStyle]:
        """
        Retrieve a built-in style or an owned custom translation style.

        Parameters
        ----------
        translation_style_id : str
            Built-in or custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TranslationStyle]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_translation_style(
        self,
        translation_style_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        instructions: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TranslationStyle]:
        """
        Rename an owned custom style or replace its instructions. Changed instructions
        are safety-validated again and invalidate translations cached under this style.
        Built-in styles cannot be modified, and a custom style's target language is immutable.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        name : typing.Optional[str]
            New display name. Omit to leave unchanged.

        instructions : typing.Optional[str]
            Replacement style-only instructions. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TranslationStyle]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="PATCH",
            json={
                "name": name,
                "instructions": instructions,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyle,
                    parse_obj_as(
                        type_=TranslationStyle,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 503:
                raise TranslationStyleValidationUnavailable(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_translation_style(
        self, translation_style_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[TranslationStyleDeleteResponse]:
        """
        Delete an owned custom translation style. Built-in styles cannot be deleted.

        Parameters
        ----------
        translation_style_id : str
            Custom translation style ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TranslationStyleDeleteResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/translation-styles/{jsonable_encoder(translation_style_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TranslationStyleDeleteResponse,
                    parse_obj_as(
                        type_=TranslationStyleDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise AuthenticationError(headers=dict(_response.headers))
            if _response.status_code == 404:
                raise TranslationStyleNotFound(headers=dict(_response.headers))
            if _response.status_code == 400:
                raise InvalidTranslationStyle(headers=dict(_response.headers))
            if _response.status_code == 429:
                raise RateLimitError(headers=dict(_response.headers))
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
