# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from . import balance, batch_transcribe, categories, link, maishiv, timestamps, transcribe, utils
    from .balance import Balance, UserNotFound
    from .categories import (
        AddTranscriptionToCategoryRequest,
        AddTranscriptionToCategoryResponse,
        Category,
        CategoryAlreadyExists,
        CategoryNotFound,
        CategoryTranscription,
        CreateCategoryRequest,
        DeleteCategoryResponse,
        RemoveTranscriptionFromCategoryResponse,
        UpdateCategoryRequest,
    )
    from .client import AsyncSoferAI, SoferAI
    from .environment import SoferAIEnvironment
    from .link import LinkError, LinkNotFound, LinkNotSupported, LinkRequest, LinkResponse, Site
    from .maishiv import (
        AddKnowledgeBaseDocumentRequest,
        AddKnowledgeBaseDocumentResponse,
        RemoveKnowledgeBaseDocumentResponse,
    )
    from .timestamps import Confidence, OutlineRequest, OutlineTopic, UpdateTimestampsRequest
    from .transcribe import (
        AuthenticationError,
        BatchAudioSource,
        BatchFileContentType,
        BatchFileCreateFromRssRequest,
        BatchFileCreateFromRssResponse,
        BatchFileDetail,
        BatchFileMetadata,
        BatchFileStatus,
        BatchFileSummary,
        BatchFileUploadRequest,
        BatchFileUploadResponse,
        BatchItemNotFound,
        BatchManifestAudioSource,
        BatchNotFound,
        BatchStatus,
        BatchStatusResponse,
        BatchTranscriptionRequest,
        BatchTranscriptionRequestInfo,
        BatchTranscriptionResponse,
        Language,
        LettersLanguage,
        ListBatchFilesResponse,
        ProcessingMode,
        RateLimitError,
        Status,
        Timestamp,
        Transcription,
        TranscriptionId,
        TranscriptionInfo,
        TranscriptionNotFound,
        TranscriptionRequest,
        TranscriptionRequestInfo,
        TranscriptionSummary,
        TranscriptionTranslationRequest,
        TranscriptionTranslationSegment,
        TranscriptionTranslationStatus,
    )
    from .utils import DurationRequest, DurationResponse
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AddKnowledgeBaseDocumentRequest": ".maishiv",
    "AddKnowledgeBaseDocumentResponse": ".maishiv",
    "AddTranscriptionToCategoryRequest": ".categories",
    "AddTranscriptionToCategoryResponse": ".categories",
    "AsyncSoferAI": ".client",
    "AuthenticationError": ".transcribe",
    "Balance": ".balance",
    "BatchAudioSource": ".transcribe",
    "BatchFileContentType": ".transcribe",
    "BatchFileCreateFromRssRequest": ".transcribe",
    "BatchFileCreateFromRssResponse": ".transcribe",
    "BatchFileDetail": ".transcribe",
    "BatchFileMetadata": ".transcribe",
    "BatchFileStatus": ".transcribe",
    "BatchFileSummary": ".transcribe",
    "BatchFileUploadRequest": ".transcribe",
    "BatchFileUploadResponse": ".transcribe",
    "BatchItemNotFound": ".transcribe",
    "BatchManifestAudioSource": ".transcribe",
    "BatchNotFound": ".transcribe",
    "BatchStatus": ".transcribe",
    "BatchStatusResponse": ".transcribe",
    "BatchTranscriptionRequest": ".transcribe",
    "BatchTranscriptionRequestInfo": ".transcribe",
    "BatchTranscriptionResponse": ".transcribe",
    "Category": ".categories",
    "CategoryAlreadyExists": ".categories",
    "CategoryNotFound": ".categories",
    "CategoryTranscription": ".categories",
    "Confidence": ".timestamps",
    "CreateCategoryRequest": ".categories",
    "DeleteCategoryResponse": ".categories",
    "DurationRequest": ".utils",
    "DurationResponse": ".utils",
    "Language": ".transcribe",
    "LettersLanguage": ".transcribe",
    "LinkError": ".link",
    "LinkNotFound": ".link",
    "LinkNotSupported": ".link",
    "LinkRequest": ".link",
    "LinkResponse": ".link",
    "ListBatchFilesResponse": ".transcribe",
    "OutlineRequest": ".timestamps",
    "OutlineTopic": ".timestamps",
    "ProcessingMode": ".transcribe",
    "RateLimitError": ".transcribe",
    "RemoveKnowledgeBaseDocumentResponse": ".maishiv",
    "RemoveTranscriptionFromCategoryResponse": ".categories",
    "Site": ".link",
    "SoferAI": ".client",
    "SoferAIEnvironment": ".environment",
    "Status": ".transcribe",
    "Timestamp": ".transcribe",
    "Transcription": ".transcribe",
    "TranscriptionId": ".transcribe",
    "TranscriptionInfo": ".transcribe",
    "TranscriptionNotFound": ".transcribe",
    "TranscriptionRequest": ".transcribe",
    "TranscriptionRequestInfo": ".transcribe",
    "TranscriptionSummary": ".transcribe",
    "TranscriptionTranslationRequest": ".transcribe",
    "TranscriptionTranslationSegment": ".transcribe",
    "TranscriptionTranslationStatus": ".transcribe",
    "UpdateCategoryRequest": ".categories",
    "UpdateTimestampsRequest": ".timestamps",
    "UserNotFound": ".balance",
    "__version__": ".version",
    "balance": ".balance",
    "batch_transcribe": ".batch_transcribe",
    "categories": ".categories",
    "link": ".link",
    "maishiv": ".maishiv",
    "timestamps": ".timestamps",
    "transcribe": ".transcribe",
    "utils": ".utils",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddKnowledgeBaseDocumentRequest",
    "AddKnowledgeBaseDocumentResponse",
    "AddTranscriptionToCategoryRequest",
    "AddTranscriptionToCategoryResponse",
    "AsyncSoferAI",
    "AuthenticationError",
    "Balance",
    "BatchAudioSource",
    "BatchFileContentType",
    "BatchFileCreateFromRssRequest",
    "BatchFileCreateFromRssResponse",
    "BatchFileDetail",
    "BatchFileMetadata",
    "BatchFileStatus",
    "BatchFileSummary",
    "BatchFileUploadRequest",
    "BatchFileUploadResponse",
    "BatchItemNotFound",
    "BatchManifestAudioSource",
    "BatchNotFound",
    "BatchStatus",
    "BatchStatusResponse",
    "BatchTranscriptionRequest",
    "BatchTranscriptionRequestInfo",
    "BatchTranscriptionResponse",
    "Category",
    "CategoryAlreadyExists",
    "CategoryNotFound",
    "CategoryTranscription",
    "Confidence",
    "CreateCategoryRequest",
    "DeleteCategoryResponse",
    "DurationRequest",
    "DurationResponse",
    "Language",
    "LettersLanguage",
    "LinkError",
    "LinkNotFound",
    "LinkNotSupported",
    "LinkRequest",
    "LinkResponse",
    "ListBatchFilesResponse",
    "OutlineRequest",
    "OutlineTopic",
    "ProcessingMode",
    "RateLimitError",
    "RemoveKnowledgeBaseDocumentResponse",
    "RemoveTranscriptionFromCategoryResponse",
    "Site",
    "SoferAI",
    "SoferAIEnvironment",
    "Status",
    "Timestamp",
    "Transcription",
    "TranscriptionId",
    "TranscriptionInfo",
    "TranscriptionNotFound",
    "TranscriptionRequest",
    "TranscriptionRequestInfo",
    "TranscriptionSummary",
    "TranscriptionTranslationRequest",
    "TranscriptionTranslationSegment",
    "TranscriptionTranslationStatus",
    "UpdateCategoryRequest",
    "UpdateTimestampsRequest",
    "UserNotFound",
    "__version__",
    "balance",
    "batch_transcribe",
    "categories",
    "link",
    "maishiv",
    "timestamps",
    "transcribe",
    "utils",
]
