# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawInternalClient, RawInternalClient
from .types.auto_generate_title_response import AutoGenerateTitleResponse
from .types.title_update_mode import TitleUpdateMode

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InternalClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInternalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInternalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInternalClient
        """
        return self._raw_client

    def auto_generate_title(
        self,
        transcription_id: uuid.UUID,
        *,
        mode: typing.Optional[TitleUpdateMode] = OMIT,
        separator: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutoGenerateTitleResponse:
        """
        Auto-generate and persist a title for a transcription.

        Parameters
        ----------
        transcription_id : uuid.UUID
            ID of the transcription to title

        mode : typing.Optional[TitleUpdateMode]
            Whether to replace the current title or append the generated title to it.

        separator : typing.Optional[str]
            Separator used between the existing title and generated title when mode is append.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutoGenerateTitleResponse

        Examples
        --------
        import uuid

        from soferai import SoferAI

        client = SoferAI(
            api_key="YOUR_API_KEY",
        )
        client.internal.auto_generate_title(
            transcription_id=uuid.UUID(
                "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            ),
        )
        """
        _response = self._raw_client.auto_generate_title(
            transcription_id, mode=mode, separator=separator, request_options=request_options
        )
        return _response.data


class AsyncInternalClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInternalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInternalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInternalClient
        """
        return self._raw_client

    async def auto_generate_title(
        self,
        transcription_id: uuid.UUID,
        *,
        mode: typing.Optional[TitleUpdateMode] = OMIT,
        separator: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AutoGenerateTitleResponse:
        """
        Auto-generate and persist a title for a transcription.

        Parameters
        ----------
        transcription_id : uuid.UUID
            ID of the transcription to title

        mode : typing.Optional[TitleUpdateMode]
            Whether to replace the current title or append the generated title to it.

        separator : typing.Optional[str]
            Separator used between the existing title and generated title when mode is append.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AutoGenerateTitleResponse

        Examples
        --------
        import asyncio
        import uuid

        from soferai import AsyncSoferAI

        client = AsyncSoferAI(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.internal.auto_generate_title(
                transcription_id=uuid.UUID(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.auto_generate_title(
            transcription_id, mode=mode, separator=separator, request_options=request_options
        )
        return _response.data
