# This file was auto-generated by Fern from our API Definition.

import typing
import uuid
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.auto_generate_title_response import AutoGenerateTitleResponse
from .types.title_update_mode import TitleUpdateMode

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawInternalClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def auto_generate_title(
        self,
        transcription_id: uuid.UUID,
        *,
        mode: typing.Optional[TitleUpdateMode] = OMIT,
        separator: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AutoGenerateTitleResponse]:
        """
        Auto-generate and persist a title for a transcription.

        Parameters
        ----------
        transcription_id : uuid.UUID
            ID of the transcription to title

        mode : typing.Optional[TitleUpdateMode]
            Whether to replace the current title or append the generated title to it.

        separator : typing.Optional[str]
            Separator used between the existing title and generated title when mode is append.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AutoGenerateTitleResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/internal/transcriptions/{jsonable_encoder(transcription_id)}/auto-title",
            method="POST",
            json={
                "mode": mode,
                "separator": separator,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AutoGenerateTitleResponse,
                    parse_obj_as(
                        type_=AutoGenerateTitleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInternalClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def auto_generate_title(
        self,
        transcription_id: uuid.UUID,
        *,
        mode: typing.Optional[TitleUpdateMode] = OMIT,
        separator: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AutoGenerateTitleResponse]:
        """
        Auto-generate and persist a title for a transcription.

        Parameters
        ----------
        transcription_id : uuid.UUID
            ID of the transcription to title

        mode : typing.Optional[TitleUpdateMode]
            Whether to replace the current title or append the generated title to it.

        separator : typing.Optional[str]
            Separator used between the existing title and generated title when mode is append.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AutoGenerateTitleResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/internal/transcriptions/{jsonable_encoder(transcription_id)}/auto-title",
            method="POST",
            json={
                "mode": mode,
                "separator": separator,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AutoGenerateTitleResponse,
                    parse_obj_as(
                        type_=AutoGenerateTitleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
