name: conventional-pr
"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SOFERAI_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SOFERAI_BOT_PRIVATE_SIGNING_KEY }}

      - name: Rename PR if needed
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          PR_TITLE=$(gh pr view --json title -q .title || echo '')
          if [[ $PR_TITLE =~ Fern[[:space:]]Regeneration[[:space:]]--[[:space:]]([A-Za-z]+)[[:space:]]([0-9]{1,2}),[[:space:]]([0-9]{4})$ ]]; then
            MONTH=$(echo ${BASH_REMATCH[1]} | tr '[:upper:]' '[:lower:]')
            DAY=${BASH_REMATCH[2]}
            YEAR=${BASH_REMATCH[3]}
            NEW_TITLE="feat(fern): regeneration $MONTH $DAY, $YEAR"
            gh pr edit --title "$NEW_TITLE"
          fi

      - uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          # to override config-conventional rules, specify a relative path to your rules module, actions/checkout is required for this setting!
          # commitlintRulesPath: './commitlint.rules.js' # default: undefined
          # if the PR contains a single commit, fail if the commit message and the PR title do not match
          commitTitleMatch: 'true' # default: 'true'
          # if you squash merge PRs and enabled "Default to PR title for squash merge commits", you can disable all linting of commits
          ignoreCommits: 'true' # default: 'false'